services:
  pollen-server:
    image: ifiocco/pollen
    container_name: pollen-server
    cpus: 3
    restart: on-failure:3
    mem_limit: 2048m
    mem_reservation: 512m
    ports:
      - "4000:4000"
    tty: true
    networks:
      - dev
    volumes:
      - .:/var/www/pollen

# Network
networks:
  dev:
    driver: bridge

